In [26]:
!pip install --pre tabnine

ERROR: Could not find a version that satisfies the requirement tabnine (from versions: none)
ERROR: No matching distribution found for tabnine


In [2]:
import numpy as np

In [3]:
 list_1d = [1,2,3,4,5,6,7,8,9]

In [4]:
np.array(list_1d)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
list_2d = [[1,2,3],[4,5,6]]

In [8]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [9]:
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace((1,1), (10,5), 10)

array([[ 1.        ,  1.        ],
       [ 2.        ,  1.44444444],
       [ 3.        ,  1.88888889],
       [ 4.        ,  2.33333333],
       [ 5.        ,  2.77777778],
       [ 6.        ,  3.22222222],
       [ 7.        ,  3.66666667],
       [ 8.        ,  4.11111111],
       [ 9.        ,  4.55555556],
       [10.        ,  5.        ]])

In [14]:
np.random.rand(4)

array([0.71740858, 0.3979413 , 0.36045889, 0.67488674])

In [15]:
np.random.rand(3,4)

array([[0.25585491, 0.97484722, 0.99309467, 0.36707274],
       [0.30317936, 0.47754015, 0.65096332, 0.43057196],
       [0.85942598, 0.1217602 , 0.76479194, 0.14935144]])

In [16]:
np.random.randn(5)

array([ 0.43568583,  0.47047058, -0.99815906, -0.22887521, -0.53163768])

In [18]:
np.random.randn(6,4)

array([[-0.64412768,  0.57858966, -0.10967912, -0.50136888],
       [ 0.0805471 ,  0.4892619 ,  0.12294049, -0.44016532],
       [-0.8063079 ,  0.58061358, -0.8894125 , -1.32666592],
       [-0.46722481, -1.60608661, -0.50834839, -0.54263353],
       [ 0.09280083, -0.19975622,  0.99395359,  1.5662341 ],
       [-1.21640266,  0.5180228 ,  0.41171142, -2.3610791 ]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:

my_array = np.random.randn(12)